language: node_js
sudo: false
node_js:
  - "stable"
addons:
  postgresql: "9.4"
services:
  - postgresql
before_script:
  - sh -c "psql -c 'DROP DATABASE IF EXISTS interviews;' -U postgres;"
  - sh -c "psql -c 'CREATE DATABASE interviews;' -U postgres;"
env:
  - DATABASE_URL=postgres://postgres@localhost/interviews
