---

- hosts: all
  gather_facts: no
  tasks:
    - block:
        - apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key state=present
        - apt_repository: repo="deb https://deb.nodesource.com/node_5.x trusty main" state=present
        - apt: name=nodejs state=present
      become: yes

    - block:
        - apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present
        - apt_repository: repo="deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main" state=present
        - apt: name=postgresql-9.5 state=present
      become: yes
